### ISSUE TITLE
Pipelines Docker Container

### ISSUE THREAD

**Issue by USGSsakins** [USGS-Astrogeology/PDS-Pipelines#13]
To allow for portability and easy upgrades we would like to have the pipeline framework in a Docker container.

Leverage this solution for airflow as an example https://github.com/puckel/docker-airflow?

**Comment by USGSsakins** [comment]
Let's put all Docker files into a /services folder in the repo

**Comment by AustinSanders** [comment]
@USGSsakins The docker file is actually giving me some trouble.  I'm having some trouble getting docker-compose to build an image that includes the local module.  As per [this](https://stackoverflow.com/questions/44708481/how-to-install-local-packages-using-pip-as-part-of-a-docker-build) post, it may be due to the directory structure (i.e. docker won't allow inclusion of local modules that are outside the directory containing the dockerfile).  It could also be due to the fact that I'm still fairly new to docker and may just be doing it wrong.
