### ISSUE TITLE
Run DIprocess.py inside of Airflow DAG

### ISSUE THREAD

**Issue by USGSsakins** [USGS-Astrogeology/PDS-Pipelines#14]
For the first pipeline to try out in Airflow use the DIprocess.py.  Break down this working solution as a Directed Acyclic Graph.  Figure out what makes sense for DAG steps (ie. calculate MD5 - then - update DB - ???)  Depends on #13

**Comment by AustinSanders** [comment]
This is finished as of PR #75, but it would be cool (and probably pretty easy) to parallelize it by dynamically triggering subdags as shown [here](https://airflow.incubator.apache.org/faq.html#how-can-i-create-dags-dynamically).

**Comment by AustinSanders** [comment]
It turns out it was pretty easy to get a parallel version up and running.  Since all tasks exist in the same subdag, the current implementation is somewhat of a synchronized-parallel implementation.  This means that n segments run in parallel, but iteration doesn't occur until the slowest segment is complete.  To get true parallelism, we'll have to spawn multiple subdags instead of relying on tasks within a single subdag.  

This is all due to the nature of DAGs and the inability to trigger tasks independently -- we have to trigger the entire dag or nothing at all.
