### ISSUE TITLE
maptemplate file stashed into log POW/MAP2

### ISSUE THREAD

**Issue by thareUSGS** [USGS-Astrogeology/PDS-Pipelines#179]
For any MAP2 or POW job we use to echo the created map projection template *.map, into the the created log file (near the top of the file). That would be great to see that file listed in the log again. It helps to debug.

Another option is to copy the *.map file into the download directory along side of the actual image products. This might be the easiest solution.

either will work.

**Comment by dpmayerUSGS** [comment]
+1 for adding *.map files to the download directory alongside final image products.

Jobs that that fail because of an issue with the map template don't complete normally, so the logfile that normally accompanies the final products is never created. However, the intermediate artifacts are available for inspection in the scratch workspace. We've had pretty good success referring to the *.map file in scratch to help with debugging.

We already print JSON of the commands and parameters into the SLURM log, so between that and the .map file itself, I think we're covered for internal debugging.
