### ISSUE TITLE
upc_reqs array not being processed on ingest

### ISSUE THREAD

**Issue by USGSsakins** [USGS-Astrogeology/PDS-Pipelines#261]
When a new file is ingested into the DI database, the full list of patterns in the upc_reqs array in XXX are not all being processed.  Only the first element is being applied and so files which do not match all of the patterns are being incorrectly marked as eligible for UPC processing.

Here is the line where the upc_reqs are used:

https://github.com/USGS-Astrogeology/PDS-Pipelines/blob/76a0be7769a308e4a8d35c223cf8db23d032e11f/pds_pipelines/Servicejobber.py#L67

**Comment by dpmayerUSGS** [comment]
It looks like this affects all PDS processes, not just Ingest because we rely on `getCleanName()` to locate the appropriate recipe for any given process and instrument. 

For example, an outside user recently reported that their POW job to process Cassini ISS never made it out of the queueing state. For `cassini_iss`, the upc_reqs looks like 
```
"upc_reqs": ["/data/", ".LBL"]
```
If I switch the file extension to be listed first, then POW works as expected. (Actually, the file extension needs to be switched to `".IMG"` in the recipe as well, for reasons that are peculiar to Cassini ISS, but I'll open another issue for that.)

**Comment by AustinSanders** [comment]
@USGSsakins @dpmayerUSGS I'm having trouble replicating this error.  It's true that the cassini upc_req needs to be set to .IMG within the pdsinfo.json file, but I don't think that's due to an error in the code.  This is true even when leaving the file extension as the second element in the array.

Switching the extension from .LBL to .IMG appears to be the solution.  In the case of cassini_iss, POW uses a .IMG file.  If we filter out any file that does not include both '/data/' and '.LBL', then, intuitively, we'll end up with nothing.

This does, however, present a question as to whether or not switching the upc requirement from .lbl to .img will break upc processing.

Running servicejobber after editing pdsinfo.json results in the desired functionality.

Running ingestprocess before / after editing pdsinfo.json results in the proper identification of .lbl / .img files as eligible for upc processing, respectively.

**Comment by AustinSanders** [comment]
After further discussions with @dpmayerUSGS and some digging around, we've come to the conclusion that the error is not within Servicejobber.py, and it actually doesn't have to do with the way that upc_reqs is being parsed or used.

This issue was raised due to the fact that LRO LROC WAC images are being queued alongside LRO LROC NAC images when running UPCQueueing.py.  There are two parts to this issue.

1. The information within the pds_info file is ambiguous -- it does not differentiate between NAC/WAC.  It contains a partial configuration for both instruments (filename), and a partial configuration for only NAC (upc_reqs).  This is problematic on its own due to the fact that we cannot support both NAC/WAC if we only have a single entry (currently lro_lroc_edr).
2. UPC queueing does not provide mechanisms to differentiate instruments past that of archive / volume.  If an archive / volume contains multiple instruments, UPC Queueing will inherently group them together

The immediate problem of differentiating files can be solved by targeting only the second problem.  This can be fixed by providing mechanisms that will allow UPCQueueing to better discriminate between instruments under a shared archive or volume specification.  This will include either:

1. a command line argument that allows for the specification of a substring that must be included in the filename (like inst=NAC).  This would be implemented as part of the file selection query.
2.  a means of filtering filenames based on the upc_reqs list.  This logic will be similar to that in IngestProcess, which is used to determine whether or not a file is upc eligible.  This would occur as post processing on the results of the select statement.

By fixing the second problem, we can resolve this issue, but we won't be able to support both NAC and WAC until both problems are addressed.  The first issue should be as simple as adding a separate recipe for each instrument and changing the "clean name" from 'lro_lroc_edr' to 'lro_lroc_nac' and 'lro_lroc_wac'.

**Comment by AustinSanders** [comment]
#279 resolves the second issue mentioned above.  We can deal with ambiguity within the pdsinfo file by providing upcqueueing with an additional 'filter' parameter.

The first issue (disambiguating the pdsinfo file) remains open, but I think the upcqueueing changes are enough to warrant closing this issue due to the facts that:
1. We have implemented a means of dealing with the primary cause of concern (errantly queueing multiple instruments)
2. Remaining tasks are documented in outstanding issues.
