### ISSUE TITLE
Failure referencing starttime/stoptime on ISIS error

### ISSUE THREAD

**Issue by USGSsakins** [USGS-Astrogeology/PDS-Pipelines#263]
During a UPC run which had a footprintinit ISIS error, the values in the starttime and stoptime failed on being inserted into the json_keywords table.  These keywords are not essential for an error and may not be available.  Remove the keywords:

https://github.com/USGS-Astrogeology/PDS-Pipelines/blob/1970ac35283a6930340d2e7ac2c22a12a594e398/pds_pipelines/UPC_process.py#L430-L444

It would be helpful in the error JSON to have keywords specifically for:

- [ ] The ISIS command that was run
- [ ] The file being processed

**Comment by dpmayerUSGS** [comment]
Thinking about this a little more and I'm wondering if the script was trying to insert the start/stop times with an eye towards eventually listing the products as "unmapped" in PILOT?

In this specific case, `footprintinit` failed because the image was actually a calibration image (which had a faulty label, but that's another story...) taken when the camera wasn't pointing at the moon.

If it's not possible to draw a footprint of an image on the target body because it isn't actually an image of the target body, should UPC still attempt to extract some minimum set of metadata before moving on? I think the answer to that question changes what the solution should be.

**Comment by thareUSGS** [comment]
Yes we do need to maintain a list of "unmapped" to help with collection counts (hopefully with a little metadata maintained.

**Comment by AustinSanders** [comment]
@USGSsakins @dpmayerUSGS @thareUSGS To clarify, the steps to closing this issue are to:

1. Remove references to start/stop time from jsonkeywords if an error has occurred.
2. Add a jsonkeyword that contains the ISIS command that caused the error
3. Add a jsonkeyword that contains the error message (?)
4. Add a jsonkeyword that contains the file being processed

Is this correct?

**Comment by AustinSanders** [comment]
As an add on to this issue, we should add the inputfile and isis command to the log file.

**Comment by AustinSanders** [comment]
These changes were added via #270.
