### ISSUE TITLE
FindDI_Ready.py not returning correct DI status for lro_lroc_edr

### ISSUE THREAD

**Issue by asunda99** [USGS-Astrogeology/PDS-Pipelines#264]
**Describe the bug**
`./FindDI_Ready.py --a lro_lroc_edr  `
I expected the above command to return DI Current, however it returned 627188 files that are ready for DI even though the entire archive was processed within the last 30 days. A quick SQL check of the DB verified that the first and last volumes of the archive have passed DI within that last 30 days. FindDI_Ready.py did return correctly for mro_hirise_extras, I am not sure if the bug is just for lroc or if it is larger. 

**To Reproduce**

```
cd /usgs/cdev/PDS-Pipelines/pds_pipelines
./FindDI_Ready.py --a lro_lroc_edr
```

**Expected behavior** 
Example from archive that worked properly, note that the error is with lroc. 
``` ./FindDI_Ready.py --a mro_hirise_extras
mro_hirise_extras
Database Connection Success
Archive mro_hirise_extras DI Current
```

**Additional context**
I used a simple SQL query to look at lroc volumes and verify that they DI had been passed in the last 30 days: 
`SELECT * from files WHERE archiveid = 74 AND filename like '%LROLRC_0032%';`

**Comment by dpmayerUSGS** [comment]
Upon further inspection, it appears that this isn't a bug with `FindDI_Ready.py`. It appears that a user simply mistyped the name of LROC volumes 2-4 when trying to run `DIqueueing.py` a few weeks ago. The script didn't find any entries in the database that matched the (invalid) volume names that were passed, so it added exactly 0 files from those volumes to the DI queue.

The real issue is that `DIqueueing.py` didn't provide any sort of warning that the volume names didn't exist. I will open a separate issue for that.
