### ISSUE TITLE
We need a view of the UPC database

### ISSUE THREAD

**Issue by USGSsakins** [USGS-Astrogeology/PDS-Pipelines#283]
We need a view of the UPC database to simplify the logic of searching the schema and enables consistent reuse of the database across multiple applications (such as GeoServer or ogr2ogr).  The view needs to include the following columns:

- [x] upcid
- [x] isisid
- [x] productid
- [x] source
- [x] detached_label
- [x] instrument
- [x] displayname (from instruments) _should we rename this view column to instrument?_
- [x] mission (from instruments)
- [x] spacecraft (from instruments)
- [x] targetname (from targets)
- [x] jsonkeywords (from json_keywords) _rename to keywords?_

**Comment by AustinSanders** [comment]
I'm not really sure about handling the JSONB, but I've got a prototypical view (currently named geoserver_view because I don't really know what the naming convention ought to be) on the test database.  I'll switch over to the geoserver configuration to test it out.

@USGSsakins @dpmayerUSGS Can we verify that the view is structured as intended?
