### ISSUE TITLE
UPC_process.py: What is different for error handling between 2isis and spiceinit failures?

### ISSUE THREAD

**Issue by USGSsakins** [USGS-Astrogeology/PDS-Pipelines#303]
Should the error block for "2isis" and "thmproc" errors be used for "spiceinit" failures?

https://github.com/USGS-Astrogeology/PDS-Pipelines/blob/d88df281472f9065f193d7fb0dc63646ab57971e/pds_pipelines/UPC_process.py#L359

**Comment by dpmayerUSGS** [comment]
**Failing at `*2isis`**
If processing errors on `*2isis`, there is a strong possibility that an ISIS cube was never created, so the only information available to write to the UPC database will be `EDRsource`. This appears to be what's going on at https://github.com/USGS-Astrogeology/PDS-Pipelines/blob/d88df281472f9065f193d7fb0dc63646ab57971e/pds_pipelines/UPC_process.py#L374-L375

However, the current code attempts to read an ISIS label and query the database for target and instrument names. https://github.com/USGS-Astrogeology/PDS-Pipelines/blob/d88df281472f9065f193d7fb0dc63646ab57971e/pds_pipelines/UPC_process.py#L364-L372

This is maybe not a great idea because *if* we've managed to read the ISIS label from an input product that failed at `*2isis`, the content of the label is probably invalid or otherwise corrupted. It is more likely that if an input product failed at `*2isis` that the attempt to read the label will fail. Currently, that will cause `UPC_process.py` to simply exit: 
https://github.com/USGS-Astrogeology/PDS-Pipelines/blob/d88df281472f9065f193d7fb0dc63646ab57971e/pds_pipelines/UPC_process.py#L348-L353

**What about failing at `thmproc`?**
`thmproc` is a wrapper around several other ISIS programs, including `spiceinit`, so it won't be immediately clear which program caused the error. If `thmproc` happens to fail while running `spiceinit` (that is, after it has successfully run one of the `*2isis` programs), then querying for target or instrument names may at least run normally. (See #301 for case where target or instrument names do not already exist in the database.)

We can short circuit this ambiguity by changes the THEMIS UPC recipes to explicitly call individual ISIS programs, rather than using the `thmproc` convenience wrapper. At the moment, none of the THEMIS UPC recipes appear to include `thmproc`, but I also haven't gotten to testing THEMIS as part of #281 yet, so I don't know if the current recipes are valid. If we can build UPC recipes for THEMIS that don't use `thmproc`, then we can remove it from the logic in `UPC_process.py`

**General failures after `2isis`**
All the items that `UPC_process.py` is currently looking for in the error block should exist as long as `2isis` ran normally:
https://github.com/USGS-Astrogeology/PDS-Pipelines/blob/d88df281472f9065f193d7fb0dc63646ab57971e/pds_pipelines/UPC_process.py#L417-L421
although if `spiceinit` failed, the value of `isisSerial` may be the string "Unknown."

**Comment by dpmayerUSGS** [comment]
Closing this because instrument-specific logic has been removed from `upc_process.py` since #388 
Errors are also reported more generically now.
