### ISSUE TITLE
UPC_process.py: Deal Generically with Odd/Even Detectors

### ISSUE THREAD

**Issue by dpmayerUSGS** [USGS-Astrogeology/PDS-Pipelines#325]
**Description**
`UPC_process.py` contains messy logic for dealing specifically with THEMIS processing. For example:
https://github.com/USGS-Astrogeology/PDS-Pipelines/blob/2cf655230a20899483b3885cb8a3bfd5cfc171ba/pds_pipelines/UPC_process.py#L241-L251

Much of this is motivated by the need to deal with separate files for the even and odd-numbered detectors from the THEMIS VIS instrument. Currently, THEMIS VIS is the only UPC-eligible instrument that gets split into odd/even detectors during processing, but we expect to be (re-)adding UPC support for MARCI in the near future, which also splits output between odd/even detectors after `marci2isis`. As such, it would be nice if there was a more generic way to handle odd/even detector cubes during UPC processing without having to resort to instrument-specific logic in `UPC_process.py`.

I'm not sure if this would work, but perhaps logic for dealing with odd/even detectors could be shifted into the recipe JSON for affected instruments?

**Comment by AustinSanders** [comment]
@dpmayerUSGS It looks like the only additional logic in the thmproc block is setting up variables that store the paths for even / odd output.  Since the paths are hard-coded based on inputfile anyway, I think we can delete the block entirely.

If we delete the thmproc block, then we'll default to the else block, which I think is fine.  We'll just have to add some logic within the handmos block to get even/odd path names based on inputfile.

the block could look something like:

```
elif item == 'handmos': 
     even = str(workarea) + str( 
         os.path.splitext(os.path.basename( 
             inputfile))[0]) + '.UPCoutput.raw.even.cub'
     odd = str(workarea) + str( 
         os.path.splitext(os.path.basename( 
             inputfile))[0]) + '.UPCoutput.raw.odd.cub'
     processOBJ.updateParameter('from_', even) 
     processOBJ.updateParameter('mosaic', odd)
```

That way, we can separate 

Thoughts?

**Comment by USGSsakins** [comment]
@AustinSanders Your logic looks correct to me.  I say go ahead and make the change.

**Comment by dpmayerUSGS** [comment]
Rendered obsolete by #374
