### ISSUE TITLE
Create documentation on database schema structure and purpose

### ISSUE THREAD

**Issue by USGSsakins** [USGS-Astrogeology/PDS-Pipelines#333]

**Comment by dpmayerUSGS** [comment]
The primary motivation for this issue is to document the refactored UPC database schema, including plain language descriptions of tables and fields, and what kind of information each field is meant to capture. The deliverable for this issue should include both textual descriptions and an ER diagram.

**Comment by AustinSanders** [comment]
Docs are up in the wiki
