### ISSUE TITLE
upc_process.py: Add a debug Mode That Outputs Metadata to CSV or JSON

### ISSUE THREAD

**Issue by dpmayerUSGS** [USGS-Astrogeology/PDS-Pipelines#380]
This enhancement request is inspired by a suggestion from @jlaura .

It would be nice if there was a way to run a UPC recipe and dump the results to 1 or more text files (either CSV mimicking the database table structure, or perhaps as JSON), rather than having to connect to a database instance. This could help with testing/debugging by verifying that metadata being extracted/derived during UPC processing is correct/as expected, independent of the functions that commit the metadata to the database.

This is currently a "nice to have."

**Comment by jlaura** [comment]
It is my opinion that using the `main` in `upc_process.py` does not make sense. That main is too tightly coupled to the redis/db architecture. This also suggests that upc_process main should be a bin script. 

The goal here is to make a script that takes in a data object that includes a PATH, a recipe PATH (because it looks like the `generate_isis_process` is only using the archive arg to get the recipe), runs the generated recipe, and then runs `create_json_keywords_record`. 

Potential order of operations:

- [ ] Move config information for the DB into an external config file (or allow this to run configless on import). See [here](https://flask.palletsprojects.com/en/1.1.x/config/) for Flask docs that are a good leading practice as far as I know. This would address #386.
- [ ] It looks like the `ups_id` argument that I thought needed to be returned (and therefore needed modifications for #384 and #385, can simply be ignored). Verify if this is true.
- [ ] Extract the DB stuff from `create_json_Keywords_record` (opinion: it should not be in there, these functions are all doing multiple things.) so that we have a clean, API callable func that does not know about the underlying DB layer.

The first item is potentially the largest change because it impacts how the project is used.

**Comment by dpmayerUSGS** [comment]
Closing as this enhancement is no longer a priority for the project.
