### ISSUE TITLE
POW Process Band Handling

### ISSUE THREAD

**Issue by acpaquette** [USGS-Astrogeology/PDS-Pipelines#479]
Both POW and map2 do not handle bands correctly when running their respective recipes. Currently band selection is applied on ingest (i.e. `thm2isis from=/foo/bar/I12345.QUB+9,7,5 to=I12345.cub`). Any PDS archived edr product will likely not be able to take into account this band selection, which is ~~thrown away~~ ignored in both the `from` and `to` parameters in the ingestion command.

~~This is also potentially present in map2.~~
(*Edit by @dpmayerUSGS : Unable to reproduce this issue when testing on a multi-band MAP2 job*)

This band selection needs to be either applied in a cubeatt step or applied to the next available ISIS program in the recipe.

**Comment by dpmayerUSGS** [comment]
Perhaps defining another jinja token, `{{out_bands}}` and placing it appropriately in a given recipe would be simpler?. The variable would be defined in `pow_process.py` and then passed as a kwarg to `generate_process()`.
Change the following
https://github.com/USGS-Astrogeology/PDS-Pipelines/blob/475c474dca0130f369426cafbca013690b1cd3e0/pds_pipelines/pow_process.py#L77-L82

to 

```
        # File Naming
        if '+' in jobFile:
            bandSplit = jobFile.split('+')
            inputFile = bandSplit[0]
            out_bands = '+' + bandSplit[1]
        else:
            inputFile = jobFile
            out_bands = None
```
and then a few lines later,
`        processes = generate_processes(jobFile, recipe_string, logger, no_extension_inputfile=no_extension_inputfile, out_bands=out_bands)
`

The POW recipe for a multispectral dataset, such as THEMIS IR, would then be modified such that the `from` parameter in `cam2map` looked like `"from": "{{no_extension_inputfile}}.cub{{out_bands}}"`. This should handle situations in which the user did not specify a subset of bands, the user specified a single band, or the user specified 3 bands. If a particular dataset could have `{{out_bands}}` specified earlier in the POW recipe, all the better because it will reduce the volume of data that needs to be processed downstream.
