### ISSUE TITLE
bit type conversion (scale and offset applied) going to 32bit?

### ISSUE THREAD

**Issue by thareUSGS** [USGS-Astrogeology/PDS-Pipelines#511]
John B. was helping a user with a MAP2 job and perhaps supporting a new default behavior might be warranted? 

First, this is a 16bit file with an offset and scale and the user requested 32bit float (real). While there was a conversion to 32bit during gdal_translate, the offset and scaler where never applied. In the case for 16bit -> 32bit this probably does make sense to do by default. Note ISIS 32bit cubes do not allow for scalar and offset, and thus any unscale must be applied.

I'm not sure if this can be handled in map2map or will need its own ISIS bit conversion routine. Otherwise, I guess "-unscale" could be used during the gdal_translate conversion.

**Comment by dpmayerUSGS** [comment]
@thareUSGS Is the goal to *always* apply a scale and offset (if present) to the input image?

In theory, it is easy to apply `-unscale` during the GDAL translation step (if output is anything *other* than PDS or ISIS cube), but I'm not sure how this meshes with any stretch parameters that a user may have passed in. 

Several things I don't know and would have to be tested:
- Can GDAL perform `-unscale` and stretch all in one step?
- If yes, does it unscale first and then stretch or vice versa?

**Comment by thareUSGS** [comment]
_>> always apply a scale and offset (if present) to the input image?_
I don't think so. I think maintaining the scale and offset, say during a clip or reprojection, is ideal. 

This really only impacts MAP2 jobs (and the handful of products which have a scale/offset).

Where it should be applied is when the user asks for **32bit floating point**. Doing that implies they are prepared to deal with the resulting "scientific" values (e.g. I/F). The use-case above was for a spectral dataset (Clementine UVVIS) and the expected output, because the user selected 32bit, was an image in I/F. What was returned was 32bit (but using the original 16bit unscale range). The user could have still applied the scale/offset but it makes sense we could do that for them. 

I guess test would be:
if (output type = 32bit float) then add "-unscale" to the gdal conversion.

Alternatively, a first step could be conversion to 32bit during any ISIS app run. I think any time an ISIS application outputs a 32bit file, it will automatically apply (really force) the scale/offset to the output DNs. This is because ISIS does not support the use of scale/offset in a 32bit file (only 16bit or 8bit). But that would need to be tested.

**Comment by acpaquette** [comment]
@thareUSGS Do you know the job ID from this run? I would like to be able to replicate the issue before I dive too deep into this. I can also talk to John B. (John Blalock?) to get the job number

**Comment by dpmayerUSGS** [comment]
@acpaquette See https://astrocloud.wr.usgs.gov/index.php?view=viewjob&key=c23a6c818dd1b764e96f6e25da098e78 for an example.
The input is a 16-bit image that has a scale and offset ("multiplier" and "base" in ISIS label, respectively). I asked for 32-bit output, no stretch. The result was indeed a 32-bit GeoTIFF, but the scale and offset were not applied (although GDAL faithfully preserved the scale and offset values in the label of the output file, so this information was not *lost*).

**Desired Behavior**
Instead what we'd like to happen in the example case is that the scale/offset get *applied*.

**Complications**
If the user had instead specified ISIS3 cube as the output format in the above example, it would be especially important to apply the scale and offset because the ISIS cube specification does not support values for "base" and "multiplier" other than 0 and 1, respectively. By not applying the scale and offset, their original values would be lost, and the user would not be able to apply them themselves without trying to look the values up somewhere else first.

What if the user requests 32-bit output *and* a stretch? MAP2 should apply the scale/offset first, followed by applying the requested stretch. https://astrocloud.wr.usgs.gov/index.php?view=viewjob&key=a040b3b8e29ebc6b0e4d46c1d7f8d9ce is the same as the example above, but with a stretch requested as well.
