### ISSUE TITLE
Keyword Definition File is largely incomplete

### ISSUE THREAD

**Issue by AustinSanders** [USGS-Astrogeology/PDS-Pipelines#88]
The keyword definition file in (pds-pipelines/recipe) is a json file that describes keywords and attributes of specific instruments / missions.  The file is necessary for UPC processing, but is currently only filled out for themis_ir_edr and mro_ctx.

In order to upc process any further archives, we'll need to fill out this file for additional archives.

A possible alternative to manually filling out this file (which will be a fairly arduous task) is to mine the data automatically from labels.  I'm not sure that this is viable, but I believe that it's worth looking into.

**Comment by USGSsakins** [comment]
All of the keywords can be found in the UPC database.  Originally these were created from .xml files that were ingested into the database creating:

instruments_meta row for each instrument and keywords rows defining the datatype, type name, and a description.  All of this can be read from the database for processing instead of using the keywords.json
