### ISSUE TITLE
PDSInfo file missing information

### ISSUE THREAD

**Issue by AustinSanders** [USGS-Astrogeology/PDS-Pipelines#89]
The upc processing script requires information such as "bandorder" and "bandbinquery" to be present in the PDSinfo file.  This information is currently only available for themis_ir_edr, themis_vis_edr, and mro_ctx.

It looks like the only necessary information that is missing is bandbinquery.  This should be present in the pdsinfo file for:
- [x] mro_ctx
- [x] mo_themis_vis_edr
- [x] mo_themis_ir_edr
- [x] lro_lroc_edr
- [x] cassini_iss
- [x] mro_hirise

**Comment by dpmayerUSGS** [comment]
It's not clear what the original intention of including a "bandorder" keyword in `PDSinfo.json` was. At the moment, it is only used in `UPC_process.py` in one place. That particular logic block seems to be attempting to choose a single band from a multi-band input to write out to a temporary cube using `cubeatt`. 
I /think/ the resulting single band cube is then used as the basis for running `footprintinit` and subsequently gathering some statistics for UPC with `caminfo`'

In practice, I don't think it actually matters /which/ band from a multi-band image is used for these purposes. It would make more sense to just grab the first band we see and use that. We still need to *identify* the band that is used for statistics, because that information gets recorded by UPC and appears in PILOT.

**Comment by AustinSanders** [comment]
@dpmayerUSGS mro_marci and mro_hirise both appear to use "FilterName" as the bandbinQuery, but I'm not 100% sure that I'm reading it properly.  Can you confirm this when you get a chance?

**Comment by dpmayerUSGS** [comment]
HiRISE: the BandBin group uses "Name"

MARCI: the BandBin group uses "FilterName"
