### ISSUE TITLE
LROC NAC L/R UPC Processing

### ISSUE THREAD

**Issue by dpmayerUSGS** [USGS-Astrogeology/PDS-Pipelines#94]
End to end processing of UPC eligible LROC NAC L and R images populating the internal production database (dino)

- [x] Verify keys/values for https://github.com/USGS-Astrogeology/PDS-Pipelines/blob/dev/pds_pipelines/PDSinfo.json
- [x] Verify recipe.json steps are correct for the instrument
- [x] Capturing Keywords
- [x] Adding to the database
- [x] Ready to sync to DMZ searchable databases

**Comment by AustinSanders** [comment]
Tested on production server with upcid = 15275727

All expected keywords are present except "exposureduration."

Exposureduration is a common keyword, and it is missing due to the presence of the instrument-specific "lineexposureduration" keyword.  This problem can be fixed by adding the "exposureduration" keyword to the keyword definition file and forcing it to lookup "linexposureduration" instead.  I'm not sure that this is what we want, though.  The results are consistent with what is reported by pilot -- exposureduration is missing, but lineexposureduration is present.
